# -*- coding: utf-8 -*-
"""dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cUq97tmnPxIK3BFuDfRqml85zEAfha2N
"""

import streamlit as st
import pandas as pd
import plotly.express as px

# ----------- PAGE CONFIG -----------
st.set_page_config(
    page_title="VELÉRAYF Instagram Dashboard",
    layout="wide"
)

# ----------- LUXURY THEME -----------
st.markdown(
    """
    <style>
    body {
        background-color: #0b0b0b;
    }
    .stMetric {
        background-color: #111111;
        padding: 15px;
        border-radius: 12px;
        border: 1px solid #c9a14a;
    }
    </style>
    """,
    unsafe_allow_html=True
)

# ----------- TITLE -----------
st.title("VELÉRAYF Instagram Business Dashboard")
st.write("Reporting Period: Jan 24 – Mar 1")

# ----------- METRICS -----------
col1, col2, col3, col4 = st.columns(4)

col1.metric("Followers", "130", "+106%")
col2.metric("Total Views", "6,082")
col3.metric("Accounts Reached", "1,096")
col4.metric("Profile Visits", "543")

st.divider()

# ----------- DISCOVERY -----------
st.subheader("Audience Source of Views")

audience = pd.DataFrame({
    "Type": ["Followers", "Non-Followers"],
    "Percentage": [39, 61]
})

fig1 = px.pie(audience, names="Type", values="Percentage")
st.plotly_chart(fig1, use_container_width=True)

st.info(
    "Majority of views come from non-followers, indicating strong discovery but weak conversion."
)

# ----------- CONTENT TYPE -----------
st.subheader("Content Type Performance")

content = pd.DataFrame({
    "Type": ["Posts", "Reels", "Stories"],
    "Percentage": [48, 43, 8]
})

fig2 = px.pie(content, names="Type", values="Percentage")
st.plotly_chart(fig2, use_container_width=True)

st.divider()

# ----------- TOP CONTENT -----------
st.subheader("Top Performing Content")

top_posts = pd.DataFrame({
    "Post": ["Giveaway", "Sapphire Earrings", "Emerald Ring", "Pearl Necklace"],
    "Views": [707, 630, 517, 489]
})

fig3 = px.bar(top_posts, x="Post", y="Views")
st.plotly_chart(fig3, use_container_width=True)

# ----------- AUDIENCE -----------
st.subheader("Audience Insights")

col5, col6 = st.columns(2)

gender = pd.DataFrame({
    "Gender": ["Men", "Women"],
    "Percentage": [70, 30]
})

fig4 = px.pie(gender, names="Gender", values="Percentage")
col5.plotly_chart(fig4, use_container_width=True)

age = pd.DataFrame({
    "Age Group": ["18-24", "25-34", "Others"],
    "Percentage": [74, 16, 10]
})

fig5 = px.bar(age, x="Age Group", y="Percentage")
col6.plotly_chart(fig5, use_container_width=True)

st.divider()

# ----------- STRATEGIC INSIGHTS -----------
st.subheader("Key Insights")

st.write("""
• Giveaway campaigns significantly increase reach and follower growth.
• Jewellery close-up shots outperform watch-focused posts.
• Majority of audience is young and located in Sri Lanka.
• Conversion from profile visits is currently low.
""")

st.subheader("Recommendations")

st.write("""
Increase Reel frequency to improve algorithm reach.
Maintain giveaway campaigns to drive engagement.
Add a WhatsApp or inquiry link in bio to improve conversions.
Create more female-focused jewellery content.
Post between 6–9 PM for higher engagement.
""")